In [40]:
import pandas as pd
import numpy as np
import joblib

# streamlit run app.py

model = joblib.load(r'data/catb_best_final.joblib')
model2 = joblib.load(r'data/rf_tuned_final.joblib')

In [ ]:
dat = np.array([hour, day_of_week, casualties, accident_cause, vehicles_involved, 
                         vehicle_type, driver_age, accident_area, driver_experience, lanes]).reshape(1, -1)

In [27]:
data = np.array([7.00000000e+00,  1.01490000e+04,  1.93100000e+03,  6.02857143e+01,
        5.91000000e+01,  3.80000000e+01,  5.05967742e+01,  6.40000000e+01,
        4.00000000e+01,  5.44821429e+01,  6.60000000e+01,  4.20000000e+01,
        5.69354839e+01,  7.70000000e+01,  4.50000000e+01,  5.84500000e+01,
        7.80000000e+01,  4.90000000e+01,  6.09032258e+01,  8.70000000e+01,
        5.10000000e+01,  6.31500000e+01,  9.70000000e+01,  5.30000000e+01,
        6.42580645e+01,  8.50000000e+01,  5.30000000e+01,  6.58548387e+01,
        8.80000000e+01,  5.40000000e+01,  6.97666667e+01,  1.04000000e+02,
        4.80000000e+01,  6.41935484e+01,  9.10000000e+01,  4.30000000e+01,
        5.80500000e+01,  6.90000000e+01,  3.80000000e+01,  5.18870968e+01,
        6.60000000e+01,  3.42000000e+02,  2.11200000e+03,  2.52400000e+01,
        0.00000000e+00,  0.00000000e+00,  6.22816855e+01,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  2.90000000e+01,
        5.00000000e+00,  1.00000000e+00,  0.00000000e+00,  1.94714286e+02,
        1.89000000e+02,  1.34571429e+01,  1.38285714e+02,  6.21961942e+01,
        8.57552389e+01,  9.26420375e+01,  3.80000000e+01,  1.04000000e+02,
        1.67082301e+01,  7.25826394e-01,  3.80000000e+01,  6.60000000e+01,
        5.21073349e+01,  1.16191606e+01, -3.43488920e-02,  4.20000000e+01,
        8.70000000e+01,  6.15876344e+01,  1.58189930e+01,  4.17654423e-01,
        5.10000000e+01,  9.70000000e+01,  6.89181004e+01,  9.70000000e+01,
        9.70000000e+01,  4.30000000e+01,  1.04000000e+02,  6.67789128e+01,
        1.98437433e+01,  8.83926782e-01,  2.85000000e+01,  1.76000000e+02,
        5.99805900e+05,  1.02006285e+00])

y = 166.58855442209398

In [28]:
data

array([ 7.00000000e+00,  1.01490000e+04,  1.93100000e+03,  6.02857143e+01,
        5.91000000e+01,  3.80000000e+01,  5.05967742e+01,  6.40000000e+01,
        4.00000000e+01,  5.44821429e+01,  6.60000000e+01,  4.20000000e+01,
        5.69354839e+01,  7.70000000e+01,  4.50000000e+01,  5.84500000e+01,
        7.80000000e+01,  4.90000000e+01,  6.09032258e+01,  8.70000000e+01,
        5.10000000e+01,  6.31500000e+01,  9.70000000e+01,  5.30000000e+01,
        6.42580645e+01,  8.50000000e+01,  5.30000000e+01,  6.58548387e+01,
        8.80000000e+01,  5.40000000e+01,  6.97666667e+01,  1.04000000e+02,
        4.80000000e+01,  6.41935484e+01,  9.10000000e+01,  4.30000000e+01,
        5.80500000e+01,  6.90000000e+01,  3.80000000e+01,  5.18870968e+01,
        6.60000000e+01,  3.42000000e+02,  2.11200000e+03,  2.52400000e+01,
        0.00000000e+00,  0.00000000e+00,  6.22816855e+01,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  2.90000000e+01,
        5.00000000e+00,  

In [29]:
data.shape

(90,)

In [30]:
data = data.reshape(1, -1)

In [31]:
data.shape

(1, 90)

In [33]:
data

array([[ 7.00000000e+00,  1.01490000e+04,  1.93100000e+03,
         6.02857143e+01,  5.91000000e+01,  3.80000000e+01,
         5.05967742e+01,  6.40000000e+01,  4.00000000e+01,
         5.44821429e+01,  6.60000000e+01,  4.20000000e+01,
         5.69354839e+01,  7.70000000e+01,  4.50000000e+01,
         5.84500000e+01,  7.80000000e+01,  4.90000000e+01,
         6.09032258e+01,  8.70000000e+01,  5.10000000e+01,
         6.31500000e+01,  9.70000000e+01,  5.30000000e+01,
         6.42580645e+01,  8.50000000e+01,  5.30000000e+01,
         6.58548387e+01,  8.80000000e+01,  5.40000000e+01,
         6.97666667e+01,  1.04000000e+02,  4.80000000e+01,
         6.41935484e+01,  9.10000000e+01,  4.30000000e+01,
         5.80500000e+01,  6.90000000e+01,  3.80000000e+01,
         5.18870968e+01,  6.60000000e+01,  3.42000000e+02,
         2.11200000e+03,  2.52400000e+01,  0.00000000e+00,
         0.00000000e+00,  6.22816855e+01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+0

In [38]:
pred = model.predict(data)

In [43]:
pred

array([68.10655529])

In [41]:
pred2 = model2.predict(data)

d:\Escritorio\Projects\MGP\MGP2_site_EUI_prediction\venv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


In [42]:
pred2

array([66.40964818])